services:
  db:
    image: postgres:16
    container_name: SmartRecommender-PostgreSQL
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ${PWD}/backend
      dockerfile: ${PWD}/.tools/docker/Dockerfile.backend
    container_name: SmartRecommender-Django
    command: >
      sh -c "pip install -r requirements.txt &&
             pip install psycopg2-binary djangorestframework-simplejwt Pillow colorama &&
             pip install textblob tqdm pandas numpy scikit-learn matplotlib seaborn nltk &&
             python -m textblob.download_corpora &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py createcachetable &&
             python manage.py seed &&
             python manage.py createcachetable recommendation_cache_table &&
             if [ -f check_media.py ]; then python check_media.py; fi &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ${PWD}/backend:/app
    ports:
      - "8000:8000"
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  frontend:
    build:
      context: ${PWD}/frontend
      dockerfile: ${PWD}/.tools/docker/Dockerfile.frontend
    container_name: SmartRecommender-React
    command: npm start
    volumes:
      - ${PWD}/frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  postgres_data:
