name: smartrecommender-project

services:
  db:
    image: postgres:16
    container_name: SmartRecommender-PostgreSQL
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: product_recommendation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d product_recommendation"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../../backend
      dockerfile: ../.tools/docker/Dockerfile.backend
    container_name: SmartRecommender-Django
    command: >
      sh -c "
      echo 'Waiting for database...' &&
      while ! pg_isready -h db -p 5432 -U postgres; do
        echo 'Waiting for postgres...'
        sleep 2
      done &&
      echo 'Database is ready!' &&
      pip install -r requirements.txt &&
      pip install psycopg2-binary djangorestframework-simplejwt Pillow colorama &&
      pip install textblob tqdm pandas numpy scikit-learn matplotlib seaborn nltk &&
      python -m textblob.download_corpora &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py createcachetable &&
      python manage.py seed &&
      python manage.py createcachetable recommendation_cache_table &&
      if [ -f check_media.py ]; then python check_media.py; fi &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ../../backend:/app
    ports:
      - "8000:8000"
    environment:
      - DB_PASSWORD=admin
      - DB_USER=postgres
      - DB_NAME=product_recommendation
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ../../frontend
      dockerfile: ../.tools/docker/Dockerfile.frontend
    container_name: SmartRecommender-React
    command: npm start
    volumes:
      - ../../frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  postgres_data:
